version: '3.4'

services:
    postgresql_database:
        container_name: postgresql_database
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=covid
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes:
            - pgadmin:/root/.pgadmin
    portainer:
        image: portainer/portainer
        container_name: Portainer
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Africa/Johannesburg
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/portainer/docker/portainer:/data
        ports:
            - 9000:9000
        restart: unless-stopped

    covid:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: covidselfassessment
        ports:
            - "5000:5000"
        restart: always

volumes:
    database-data:
    pgadmin: