version: '3.4'

services:
    postgresql_database:
        container_name: postgresql_database
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=covid
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes:
            - pgadmin:/root/.pgadmin
     
   migrations: 
    WAIT_HOSTS: "postgresql_database:5432"
    command: "sh -c \"/wait && alembic upgrade head\""
    depends_on: 
      - covidselfassessment
      - postgresql_database
    env_file: 
      - .env.docker
    environment: ~
    image: covidselfassessment
    restart: "no"

volumes:
    database-data:
    pgadmin:
