"""empty message

Revision ID: 24ee9e25066d
Revises: 
Create Date: 2022-03-23 21:11:33.073764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ee9e25066d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=True),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('site', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_visitor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=10), nullable=False),
    sa.Column('feedback', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag')
    )
    op.create_table('Questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('incontact', sa.String(length=5), nullable=True),
    sa.Column('temperature', sa.Float(precision=4), nullable=True),
    sa.Column('fever', sa.String(length=5), nullable=True),
    sa.Column('drycough', sa.String(length=5), nullable=True),
    sa.Column('sorethroat', sa.String(length=5), nullable=True),
    sa.Column('feverdrycough', sa.String(length=5), nullable=True),
    sa.Column('feversorethroat', sa.String(length=5), nullable=True),
    sa.Column('drycoughsorethroat', sa.String(length=5), nullable=True),
    sa.Column('difficultyinbreathing', sa.String(length=5), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Questionnaire')
    op.drop_table('Recommendations')
    op.drop_table('Employee')
    # ### end Alembic commands ###
